//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTraker.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockTrackerEntities : DbContext
    {
        public StockTrackerEntities()
            : base("name=StockTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TABLE_CATEGORY> TABLE_CATEGORY { get; set; }
        public virtual DbSet<TABLE_CUSTOMER> TABLE_CUSTOMER { get; set; }
        public virtual DbSet<TABLE_PRODUCT> TABLE_PRODUCT { get; set; }
        public virtual DbSet<TABLE_SALES> TABLE_SALES { get; set; }
    }
}
